# THIS FILE WAS GENERATED BY `build_makefile.exs`
# 554ae5b
# Mon Feb 20 06:47:02 2017 -0800
# bump-version

default: rpi3

dev_env:
	export MIX_ENV=dev

prod_env:
	export MIX_ENV=prod

clean:
	$(info Cleaning)
	rm -rf apps/NERVES_SYSTEM_*
	rm -rf apps/farmbot/_images
	rm -rf apps/nerves_system_br
	rm -rf deps
	rm -rf _build

test: dev_env
	scripts/run_tests.sh

## End default portion.

## begin rpi portion.

## rpi env
env-rpi: prod_env
	export NERVES_TARGET=rpi

## rpi build
rpi: env-rpi system-rpi firmware-rpi
	$(info Building stuff for rpi)

## rpi create-build
create-build-rpi:
	scripts/clone_system.sh rpi

## rpi system
system-rpi: create-build-rpi
	$(info Building Linux System for rpi)
	scripts/build_system.sh rpi

## rpi firmware
firmware-rpi:
	$(info Building Firmware for rpi)
	scripts/build_firmware.sh rpi

release-rpi: rpi
	scripts/build_release_images.sh rpi 3.0.6-staging.1

## end rpi portion.
## begin rpi3 portion.

## rpi3 env
env-rpi3: prod_env
	export NERVES_TARGET=rpi3

## rpi3 build
rpi3: env-rpi3 system-rpi3 firmware-rpi3
	$(info Building stuff for rpi3)

## rpi3 create-build
create-build-rpi3:
	scripts/clone_system.sh rpi3

## rpi3 system
system-rpi3: create-build-rpi3
	$(info Building Linux System for rpi3)
	scripts/build_system.sh rpi3

## rpi3 firmware
firmware-rpi3:
	$(info Building Firmware for rpi3)
	scripts/build_firmware.sh rpi3

release-rpi3: rpi3
	scripts/build_release_images.sh rpi3 3.0.6-staging.1

## end rpi3 portion.
## begin rpi2 portion.

## rpi2 env
env-rpi2: prod_env
	export NERVES_TARGET=rpi2

## rpi2 build
rpi2: env-rpi2 system-rpi2 firmware-rpi2
	$(info Building stuff for rpi2)

## rpi2 create-build
create-build-rpi2:
	scripts/clone_system.sh rpi2

## rpi2 system
system-rpi2: create-build-rpi2
	$(info Building Linux System for rpi2)
	scripts/build_system.sh rpi2

## rpi2 firmware
firmware-rpi2:
	$(info Building Firmware for rpi2)
	scripts/build_firmware.sh rpi2

release-rpi2: rpi2
	scripts/build_release_images.sh rpi2 3.0.6-staging.1

## end rpi2 portion.

## Release will build all the systems.
release: clean  release-rpi release-rpi3 release-rpi2