defmodule FarmbotCore.Asset.FarmwareInstallation.Manifest do
  defstruct package: "",
    language: "",
    author: "",
    description: "",
    url: "",
    zip: "",
    executable: "",
    args: "",
    config: %{},
    package_version: "",
    farmware_manifest_version: "",
    farmware_tools_version_requirement: ">= 0.0.0",
    farmbot_os_version_requirement: "~> 8.0",
end
