{application,mimic,
             [{applications,[kernel,stdlib,elixir,logger,tools]},
              {description,"Mocks for Elixir functions"},
              {modules,['Elixir.Mimic','Elixir.Mimic.Application',
                        'Elixir.Mimic.Cover','Elixir.Mimic.DSL',
                        'Elixir.Mimic.Error','Elixir.Mimic.Module',
                        'Elixir.Mimic.Server',
                        'Elixir.Mimic.Server.Expectation',
                        'Elixir.Mimic.Server.State',
                        'Elixir.Mimic.UnexpectedCallError',
                        'Elixir.Mimic.VerificationError']},
              {registered,[]},
              {vsn,"1.4.0"},
              {mod,{'Elixir.Mimic.Application',[]}}]}.
