{application,circuits_uart,
             [{applications,[kernel,stdlib,elixir]},
              {description,"Discover and use UARTs and serial ports in Elixir"},
              {modules,['Elixir.Circuits.UART',
                        'Elixir.Circuits.UART.Enumerator',
                        'Elixir.Circuits.UART.Framing',
                        'Elixir.Circuits.UART.Framing.FourByte',
                        'Elixir.Circuits.UART.Framing.Line',
                        'Elixir.Circuits.UART.Framing.Line.State',
                        'Elixir.Circuits.UART.Framing.None',
                        'Elixir.Circuits.UART.State']},
              {registered,[]},
              {vsn,"1.4.2"}]}.
