#!/bin/bash
SYSTEM=$1
VERSION=$2
PRIV_KEY_PATH=$3
REL_DIR=release-$VERSION
FIRM_FILE_REL=$REL_DIR/farmbot-$SYSTEM-$VERSION.fw
SIGNED_FIRM_FILE_REL=$REL_DIR/farmbot-$SYSTEM-$VERSION-signed.fw

fwup -S -s $PRIV_KEY_PATH -i $FIRM_FILE_REL -o $SIGNED_FIRM_FILE_REL
rm $FIRM_FILE_REL
